{
 "title": "Accounts service",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Accounts latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(accounts_request_latency_sec_bucket[1m])))",
     "legendFormat": "0.99 percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(accounts_request_latency_sec_bucket[1m])))",
     "legendFormat": "0.95 percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(accounts_request_latency_sec_bucket[1m])))",
     "legendFormat": "0.5 percentile"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(accounts_request_latency_sec_bucket[1m])))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Account latency (Ingress)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"accounts\"}[1m])))",
     "legendFormat": "0.99 procentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"accounts\"}[1m])))",
     "legendFormat": "0.95 procentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"accounts\"}[1m])))",
     "legendFormat": "0.5 procentile"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{path=\"/otusapp(/|$)(.*)\"}[1m])))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "RPS Accounts service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(accounts_request_count[1m]))",
     "legendFormat": "{{exported_endpoint}}"
    },
    {
     "expr": "sum (rate(accounts_request_count[1m]))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "RPS Accounts (Ingress)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_service=\"accounts\"}[1m]))"
    }
   ]
  },
  {
   "title": "RPS by statuses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (http_status) (rate(accounts_request_count[1m]))"
    }
   ]
  },
  {
   "title": "RPS by statuses (Ingress)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(status) (rate(nginx_ingress_controller_requests{ingress=\"accounts\", status!=\"500\"}[1m]))",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum (rate(nginx_ingress_controller_requests{exported_service=\"accounts\", status=\"500\"}[1m]))",
     "legendFormat": "500"
    }
   ]
  },
  {
   "title": "CPU time Accounts service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"accounts\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage Accounts service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"accounts\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}