apiVersion: v1
kind: Secret
metadata:
  name: auth-sidecar-config
stringData:
  auth-sidecar-config.yaml: |
    server:
      port: {{ .Values.authSidecar.server.port }}

    target:
      url: http://127.0.0.1:{{ .Values.service.port }}

    jwt:
      algorithm: {{ .Values.authSidecar.jwt.algorithm }}
      publicKey: {{ .Values.authSidecar.jwt.publicKey }}

    excludeAuth:
      - path: /auth
        method: GET
      - path: /profile/
        method: POST
