apiVersion: v2
name: accounts
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.5
dependencies:
- name: postgresql
  version: 9.8.9
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enableDependency
  tags:
    - database