{{- $svcPort := .Values.service.port -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-config
stringData:
  auth-config.yaml: |
    server:
      port: {{ .Values.service.port }}

    AccountService:
      url: {{ .Values.accountService.url }}
