version: "3.8"
services:
  account:
    build:
      context: ./account
    command: ["-config", "/app/app-test.yaml"]
    depends_on:
      - db
      - account-migrations
    ports:
      - 8000:8000
    volumes:
      - ./account/:/app/

  auth-sidecar:
    build:
      context: ./auth-sidecar
    command: ["-config", "/app/app-test.yaml"]
    depends_on:
      - account
    ports:
      - 8002:8002
    volumes:
      - ./auth-sidecar/:/app/

  auth:
    build:
      context: ./auth
    command: ["-config", "/app/app-test.yaml"]
    depends_on:
      - account
    ports:
      - 8001:8001
    volumes:
      - ./auth/:/app/

  billing:
    build:
      context: ./billing
    command: [ "-config", "/app/app-test.yaml" ]
    depends_on:
      - billing-migrations
      - db
    ports:
      - 8020:8020
    volumes:
      - ./billing/:/app/

  account-migrations:
    build:
      context: ./account/migrations
    command: [
      "db:5432", "--",
      "migrate", "-path", "/migrations/",
      "-database", "postgres://tom:tom@db:5432/account?sslmode=disable", "up"
    ]
    depends_on:
      - db
      - init-db

  billing-migrations:
    build:
      context: ./billing/migrations
    command: [
        "db:5432", "--",
        "migrate", "-path", "/migrations/",
        "-database", "postgres://tom:tom@db:5432/billing?sslmode=disable", "up"
    ]
    depends_on:
      - db
      - init-db

  init-db:
    build:
      context: ./init_db
    command: [
      "db:5432", "--",
      "psql", "postgres://tom:tom@db:5432/tom?sslmode=disable",
      "-f", "/sql/init_db.sql",
    ]
    depends_on:
      - db

  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=tom
      - POSTGRES_PASSWORD=tom
      - POSTGRES_DB=tom
    ports:
      - 5432:5432

volumes:
  postgres_data:
