{{- $svcPort := .Values.service.port -}}
{{- $dbHost := .Values.postgresql.host -}}
{{- $dbPort := .Values.postgresql.service.port -}}
{{- $dbUser := .Values.postgresql.postgresqlUsername -}}
{{- $dbPassword := .Values.postgresql.postgresqlPassword -}}
{{- $dbDatabase := .Values.postgresql.postgresqlDatabase -}}
{{- $dbOptions := .Values.postgresql.options -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-config
stringData:
  account-config.yaml: |
    server:
      port: {{ $svcPort }}

    database:
      dsn: "postgres://{{ $dbUser }}:{{ $dbPassword }}@{{ $dbHost}}:{{ $dbPort}}/{{ $dbDatabase }}?{{ $dbOptions }}"
